### PR TITLE
moved `debug` package, updated test setup

### PR DESCRIPTION
**Pull request by hellatan**
- this package does not install correctly when `debug` is in devDependencies since it is `require`d in `./lib/index.js`. 
- updated testing dependencies

### CODE REVIEW

**Comment by hellatan** [comment]
I had two PRs but one was so minor and the other one depended on the minor one so I combined them into two.

**Comment by pofallon** [comment]
Good stuff - thanks!

**Comment by pofallon** [comment]
Published to npm as [v0.0.2](https://www.npmjs.com/package/metalsmith-jquery)

**Comment by hellatan** [comment]
:+1:

**Pull request merged**
